# -*- coding: utf-8 -*-
"""Day 7_rule_based_extractorrule_based_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1guiygAY51TgNo7A6HsOPTV02FsGYT1Dj
"""

skills = [
    "python",
    "sql",
    "power bi",
    "tableau",
    "excel",
    "aws"
]

print(skills)

def extract_skills(text):
    found = []

    for skill in skills:
        if skill in text.lower():
            found.append(skill)

    return found

text = "We are looking for candidates with Python, SQL, Power BI and AWS experience."

print(text)

result = extract_skills(text)

print(result)